ALTER TABLE books ADD COLUMN pages INTEGER NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN translator TEXT;
ALTER TABLE books ADD COLUMN series TEXT;
ALTER TABLE books ADD COLUMN age_target TEXT NOT NULL DEFAULT 'Todos';
ALTER TABLE books ADD COLUMN binding_type TEXT NOT NULL DEFAULT 'Tapa blanda';
ALTER TABLE books ADD COLUMN language TEXT NOT NULL DEFAULT 'ES';
ALTER TABLE books ADD COLUMN published_at DATE;
